name: CI

on:
  pull_request:
  push:
    branches:
      - main

jobs:
  lint-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install .[dev]
      - name: Run formatters
        run: |
          black --check .
          isort --check-only .
      - name: Run lint
        run: ruff check .
      - name: Type check
        run: mypy backend
      - name: Run tests
        run: pytest
